# Generated by Django 3.2.6 on 2021-10-18 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseclass',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('createdat', models.DateField(auto_now_add=True)),
                ('updatedat', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.baseclass')),
                ('categoryname', models.CharField(max_length=50)),
            ],
            bases=('home.baseclass',),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.baseclass')),
                ('Question', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=5)),
                ('categoryname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            bases=('home.baseclass',),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.baseclass')),
                ('answer', models.CharField(max_length=30)),
                ('iscorrect', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.questions')),
            ],
            bases=('home.baseclass',),
        ),
    ]
