# Generated by Django 3.2.6 on 2021-10-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Question',
            new_name='questionname',
        ),
    ]
